### PR TITLE
Fix Glaxx blocks and change type counting

### PR DESCRIPTION
**Pull request by DeadSix27**
Fixed Glaxx blocks not being see-through.
Changed type counting to start from 0.

### CODE REVIEW

**Comment by ChloeDawn** [comment]
Have you tested to make sure BlockRenderLayer.TRANSLUCENT behaves for all other block types? It *should* work fine but I want to be sure.

**Comment by DeadSix27** [comment]
@InsomniaKitten 

My MC-Modding knowledge is rather limited.

What does "behaves for all other block types" mean exactly?

As far as I can see only `Glaxx` is ever `BlockRenderLayer.TRANSLUCENT`. 
`register(new BlockXtone("glaxx", new ItemStack(Blocks.GLASS)).setSeeThrough());`

And that works just fine, with and without OptiFine. 

image

**Comment by TehNut** [comment]
The off by one was intentional as most users don't have a development background and find starting at 0 odd

**Comment by TehNut** [comment]
If you remove the type count change, I'll pull this, though I still need to fix them causing shadows

**Comment by DeadSix27** [comment]
@TehNut reverted it, btw, I tried it myself but failed to add the flat lamps. That's beyond my knowledge of forge and co. Are you going to add them?

**Comment by TehNut** [comment]
Unsure. Possibly

**Comment by TehNut** [comment]
Formatting nitpick, could you re-add the space after the `+`

**Comment by TehNut** [comment]
I'll cherry-pick to 1.11 when I get home

**Pull request merged**
